
server:
  port: 8100

spring:
  application:
    name: cloud-greeter-config
  profiles:
    active: native

logging:
  file: logs/${spring.application.name}.log
  level:
    org.springframework.cloud: DEBUG
    com.inmensia: DEBUG

---

spring:
  profiles: native
  cloud:
    config:
      server:
        native:
          searchLocations: ${CLOUD_GREETER_CONFIG_PATH}
